import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final localizations = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(localizations != null, 'AppLocalizations not found in context');
    return localizations!;
  }

  static const Map<String, String> _en = {
    'N/A': 'N/A',
    'Dashboard': 'Dashboard',
    'Appointments': 'Appointments',
    'Patients': 'Patients',
    'Diagnosis': 'Diagnosis',
    'Treatment Resistance': 'Treatment Resistance',
    'Schedule': 'Schedule',
    'Settings': 'Settings',
    'Doctor': 'Doctor',
    'Logout': 'Logout',
    'Toggle theme': 'Toggle theme',
    'Light mode': 'Light mode',
    'Dark mode': 'Dark mode',
    'Logged out successfully': 'Logged out successfully',
    'Page': 'Page',
    'CureVoo': 'CureVoo',
    'Welcome Back, Doctor': 'Welcome Back, Doctor',
    'Sign in to access your dashboard': 'Sign in to access your dashboard',
    'Email Address': 'Email Address',
    'Password': 'Password',
    'Remember me': 'Remember me',
    'Forgot Password?': 'Forgot Password?',
    'Sign In': 'Sign In',
    'OR': 'OR',
    "Don't have an account? ": "Don't have an account? ",
    'Create Account': 'Create Account',
    'Why Choose CureVoo?': 'Why Choose CureVoo?',
    'Comprehensive Diagnosis & Treatment Plans':
        'Comprehensive Diagnosis & Treatment Plans',
    'Secure Patient Records Management': 'Secure Patient Records Management',
    'Efficient Appointment Scheduling': 'Efficient Appointment Scheduling',
    'Please enter your email': 'Please enter your email',
    'Please enter your password': 'Please enter your password',
    'Please enter a password': 'Please enter a password',
    'Password must be at least 6 characters':
        'Password must be at least 6 characters',
    'Password must be 12 to 128 characters':
        'Password must be 12 to 128 characters',
    'Password must include a lowercase letter, uppercase letter, number, and symbol':
        'Password must include a lowercase letter, uppercase letter, number, and symbol',
    'Password must not contain spaces': 'Password must not contain spaces',
    'Forgot Password': 'Forgot Password',
    'Verify OTP': 'Verify OTP',
    'Enter the OTP sent to your email.': 'Enter the OTP sent to your email.',
    'OTP Code': 'OTP Code',
    '6-digit code': '6-digit code',
    'Please enter the OTP': 'Please enter the OTP',
    'OTP must be 6 digits': 'OTP must be 6 digits',
    'Demo OTP: 123456': 'Demo OTP: 123456',
    'Invalid OTP. Please try again.': 'Invalid OTP. Please try again.',
    'OTP verified successfully.': 'OTP verified successfully.',
    'Reset Password': 'Reset Password',
    'Create a new password for your account.':
        'Create a new password for your account.',
    'New Password': 'New Password',
    'Confirm Password': 'Confirm Password',
    'Please enter a new password': 'Please enter a new password',
    'Please confirm your password': 'Please confirm your password',
    'Passwords do not match': 'Passwords do not match',
    'Save New Password': 'Save New Password',
    'Password updated successfully.': 'Password updated successfully.',
    'Change Password': 'Change Password',
    'Current Password': 'Current Password',
    'Enter your current password': 'Enter your current password',
    'Enter your new password': 'Enter your new password',
    'Confirm your new password': 'Confirm your new password',
    'Please enter your current password': 'Please enter your current password',
    'Update your password by entering your current password first.':
        'Update your password by entering your current password first.',
    'Password changed successfully.': 'Password changed successfully.',
    'Failed to change password. Please try again.':
        'Failed to change password. Please try again.',
    'New password must be different from current password':
        'New password must be different from current password',
    'Dashboard Overview': 'Dashboard Overview',
    'Total Patients': 'Total Patients',
    'Upcoming Appointments': 'Upcoming Appointments',
    'Pending Appointments': 'Pending Appointments',
    'Latest AI Prediction': 'Latest AI Prediction',
    'Welcome back, Dr.': 'Welcome back, Dr.',
    "Here's what's happening today.": "Here's what's happening today.",
    "Welcome back, Dr. Johnson! Here's what's happening today.":
        "Welcome back, Dr. Johnson! Here's what's happening today.",
    'Appointment Management': 'Appointment Management',
    'Manage and schedule patient appointments':
        'Manage and schedule patient appointments',
    'Create a new appointment for a patient':
        'Create a new appointment for a patient',
    'Edit Appointment': 'Edit Appointment',
    'Update Appointment': 'Update Appointment',
    'Update appointment details': 'Update appointment details',
    'Select patient': 'Select patient',
    'Phone Number': 'Phone Number',
    'Date': 'Date',
    'Select date': 'Select date',
    'Select time': 'Select time',
    'Appointment Type': 'Appointment Type',
    'Select appointment type': 'Select appointment type',
    'Please select a patient': 'Please select a patient',
    'Please select a date': 'Please select a date',
    'Please select time': 'Please select time',
    'Please select appointment type': 'Please select appointment type',
    'Additional Notes': 'Additional Notes',
    'Add notes': 'Add notes',
    'Status': 'Status',
    'Appointment created successfully': 'Appointment created successfully',
    'Appointment updated successfully': 'Appointment updated successfully',
    'Appointment deleted successfully': 'Appointment deleted successfully',
    'Delete Appointment': 'Delete Appointment',
    'Are you sure you want to delete this appointment?':
        'Are you sure you want to delete this appointment?',
    'Failed to delete appointment.': 'Failed to delete appointment.',
    'Appointment Details': 'Appointment Details',
    'Review appointment information and notes':
        'Review appointment information and notes',
    'No available times found': 'No available times found',
    'You cannot add appointments to past days':
        'You cannot add appointments to past days',
    'All Appointments': 'All Appointments',
    'Search appointments...': 'Search appointments...',
    'Date Range': 'Date Range',
    'Time': 'Time',
    'Type': 'Type',
    'View': 'View',
    'Confirmed': 'Confirmed',
    'Pending': 'Pending',
    'Cancelled': 'Cancelled',
    'Check-up': 'Check-up',
    'Follow-up': 'Follow-up',
    'Consultation': 'Consultation',
    'Vaccination': 'Vaccination',
    'Emergency': 'Emergency',
    'Routine': 'Routine',
    "Today's Appointments": "Today's Appointments",
    'Recent Patients': 'Recent Patients',
    'Weekly Schedule': 'Weekly Schedule',
    'View and manage your weekly appointments':
        'View and manage your weekly appointments',
    'Nov 16 - Nov 22, 2025': 'Nov 16 - Nov 22, 2025',
    'This Week': 'This Week',
    'All Patients': 'All Patients',
    'Filter': 'Filter',
    'Add New Patient': 'Add New Patient',
    'Cancel': 'Cancel',
    'Patient added successfully!': 'Patient added successfully!',
    'Please fill all fields': 'Please fill all fields',
    'Add Patient': 'Add Patient',
    'Close': 'Close',
    'Edit': 'Edit',
    'Edit Patient': 'Edit Patient',
    'Patient updated successfully!': 'Patient updated successfully!',
    'Update': 'Update',
    'Patient Management': 'Patient Management',
    'View and manage patient records': 'View and manage patient records',
    'Patient': 'Patient',
    'Age': 'Age',
    'Gender': 'Gender',
    'Phone': 'Phone',
    'Last Visit': 'Last Visit',
    'Condition': 'Condition',
    'Actions': 'Actions',
    'Language': 'Language',
    'Application Language': 'Application Language',
    'Choose your preferred language': 'Choose your preferred language',
    'English': 'English',
    'Arabic': 'Arabic',
    'to': 'to',
    'Collapse sidebar': 'Collapse sidebar',
    'Expand sidebar': 'Expand sidebar',
    'Cancer Diagnosis & Examination': 'Cancer Diagnosis & Examination',
    'Complete the diagnostic form and upload X-ray images for analysis':
        'Complete the diagnostic form and upload X-ray images for analysis',
    'Patient Selection': 'Patient Selection',
    'Choose an option': 'Choose an option',
    'Select Existing Patient': 'Select Existing Patient',
    'Create New Patient': 'Create New Patient',
    'Patient Selected': 'Patient Selected',
    'Creating New Patient': 'Creating New Patient',
    'Please fill in the patient information below':
        'Please fill in the patient information below',
    'Select Patient *': 'Select Patient *',
    'Choose a patient from the list': 'Choose a patient from the list',
    'Patient Information': 'Patient Information',
    'Enter patient name': 'Enter patient name',
    'Enter age': 'Enter age',
    'Select gender': 'Select gender',
    'Patient ID': 'Patient ID',
    'Enter patient ID': 'Enter patient ID',
    'Patient information auto-filled from selected patient':
        'Patient information auto-filled from selected patient',
    'Cancer Type & Location': 'Cancer Type & Location',
    'Cancer Type': 'Cancer Type',
    'Select cancer type': 'Select cancer type',
    'Tumor Location': 'Tumor Location',
    'Specify exact location': 'Specify exact location',
    'Tumor Size (cm)': 'Tumor Size (cm)',
    'Enter tumor size': 'Enter tumor size',
    'Symptoms & Medical History': 'Symptoms & Medical History',
    'Current Symptoms': 'Current Symptoms',
    'Describe current symptoms': 'Describe current symptoms',
    'Symptom Duration': 'Symptom Duration',
    'Do you suffer from shortness of breath?':
        'Do you suffer from shortness of breath?',
    'Is there a cough accompanied by blood?':
        'Is there a cough accompanied by blood?',
    'Is there chest pain?': 'Is there chest pain?',
    'Has fainting or severe dizziness occurred?':
        'Has fainting or severe dizziness occurred?',
    'Has there been weight loss in the recent period?':
        'Has there been weight loss in the recent period?',
    'Are you a smoker?': 'Are you a smoker?',
    'What is your profession?': 'What is your profession?',
    'Enter profession': 'Enter profession',
    'Is there hoarseness of voice?': 'Is there hoarseness of voice?',
    'Family History of Cancer': 'Family History of Cancer',
    'Select option': 'Select option',
    'Previous Treatment History': 'Previous Treatment History',
    'List previous treatments, surgeries, or therapies':
        'List previous treatments, surgeries, or therapies',
    'Additional Questions & Answers': 'Additional Questions & Answers',
    'Add question and answer': 'Add question and answer',
    'Symptoms Section Notes': 'Symptoms Section Notes',
    'Add notes related to symptoms and medical history':
        'Add notes related to symptoms and medical history',
    'Question': 'Question',
    'Enter question': 'Enter question',
    'Answer': 'Answer',
    'Enter answer': 'Enter answer',
    'Remove': 'Remove',
    'Clear Fields': 'Clear Fields',
    'Fields cleared successfully': 'Fields cleared successfully',
    'Clinical Examination Findings': 'Clinical Examination Findings',
    'Blood Pressure': 'Blood Pressure',
    'e.g., 120/80 mmHg': 'e.g., 120/80 mmHg',
    'Heart Rate': 'Heart Rate',
    'e.g., 72 bpm': 'e.g., 72 bpm',
    'Temperature': 'Temperature',
    'e.g., 37°C': 'e.g., 37°C',
    'Weight (kg)': 'Weight (kg)',
    'Enter weight': 'Enter weight',
    'Physical Examination Notes': 'Physical Examination Notes',
    'Document physical examination findings':
        'Document physical examination findings',
    'Laboratory Test Results': 'Laboratory Test Results',
    'Blood Test Results': 'Blood Test Results',
    'CBC, tumor markers, liver function, kidney function...':
        'CBC, tumor markers, liver function, kidney function...',
    'Biopsy Results (if available)': 'Biopsy Results (if available)',
    'Histopathology findings, cell type, grade...':
        'Histopathology findings, cell type, grade...',
    'Cancer Staging Information': 'Cancer Staging Information',
    'Select stage': 'Select stage',
    'Additional Clinical Notes': 'Additional Clinical Notes',
    "Doctor's Notes & Observations": "Doctor's Notes & Observations",
    'Any additional observations, concerns, or recommendations...':
        'Any additional observations, concerns, or recommendations...',
    'X-Ray Image Upload': 'X-Ray Image Upload',
    'Click to upload X-ray images': 'Click to upload X-ray images',
    'PNG, JPG, DICOM up to 10MB': 'PNG, JPG, DICOM up to 10MB',
    'Uploaded X-Ray Images': 'Uploaded X-Ray Images',
    'Diagnosis Stats': 'Diagnosis Stats',
    'Total Cases': 'Total Cases',
    'This Month': 'This Month',
    'Pending Review': 'Pending Review',
    'Generate Diagnosis Report': 'Generate Diagnosis Report',
    'This field is required': 'This field is required',
    'Please complete the highlighted required fields':
        'Please complete the highlighted required fields',
    'Diagnosis Report': 'Diagnosis Report',
    'Download PDF': 'Download PDF',
    'Print Report': 'Print Report',
    'Share': 'Share',
    'Diagnosis result summary':
        'Based on the provided information and X-ray images, preliminary analysis suggests further investigation is recommended. Please review the comprehensive report below for detailed findings and recommendations.',
    'Diagnosis report generated successfully!':
        'Diagnosis report generated successfully!',
    'Male': 'Male',
    'Female': 'Female',
    'Other': 'Other',
    'Lung Cancer': 'Lung Cancer',
    'Breast Cancer': 'Breast Cancer',
    'Prostate Cancer': 'Prostate Cancer',
    'Colorectal Cancer': 'Colorectal Cancer',
    'Skin Cancer': 'Skin Cancer',
    'Lymphoma': 'Lymphoma',
    'Leukemia': 'Leukemia',
    'Yes': 'Yes',
    'No': 'No',
    'Unknown': 'Unknown',
    'Stage 0 (In situ)': 'Stage 0 (In situ)',
    'Stage I': 'Stage I',
    'Stage II': 'Stage II',
    'Stage III': 'Stage III',
    'Stage IV': 'Stage IV',
    'Not yet determined': 'Not yet determined',
    'years old': 'years old',
    'y': 'y',
    'ID': 'ID',
    'Manage your clinic and application settings':
        'Manage your clinic and application settings',
    'Profile Information': 'Profile Information',
    'First Name': 'First Name',
    'Enter first name': 'Enter first name',
    'Last Name': 'Last Name',
    'Enter last name': 'Enter last name',
    'Email': 'Email',
    'Enter email': 'Enter email',
    'Enter phone number': 'Enter phone number',
    'Specialty': 'Specialty',
    'Enter specialty': 'Enter specialty',
    'Save Changes': 'Save Changes',
    'Profile information saved successfully!':
        'Profile information saved successfully!',
    'Clinic Settings': 'Clinic Settings',
    'Clinic Name': 'Clinic Name',
    'Enter clinic name': 'Enter clinic name',
    'Address': 'Address',
    'Enter address': 'Enter address',
    'City': 'City',
    'Enter city': 'Enter city',
    'ZIP Code': 'ZIP Code',
    'Enter ZIP code': 'Enter ZIP code',
    'Update Clinic Info': 'Update Clinic Info',
    'Clinic information updated successfully!':
        'Clinic information updated successfully!',
    'Notifications': 'Notifications',
    'Email Notifications': 'Email Notifications',
    'Receive email updates about appointments':
        'Receive email updates about appointments',
    'SMS Notifications': 'SMS Notifications',
    'Get text messages for urgent updates':
        'Get text messages for urgent updates',
    'Appointment Reminders': 'Appointment Reminders',
    'Send reminders to patients': 'Send reminders to patients',
    'Daily Summary': 'Daily Summary',
    'Receive daily summary of appointments':
        'Receive daily summary of appointments',
    'enabled': 'enabled',
    'disabled': 'disabled',
    'Working Hours': 'Working Hours',
    'Monday': 'Monday',
    'Tuesday': 'Tuesday',
    'Wednesday': 'Wednesday',
    'Thursday': 'Thursday',
    'Friday': 'Friday',
    'Saturday': 'Saturday',
    'Sunday': 'Sunday',
    'Save Working Hours': 'Save Working Hours',
    'Working hours saved successfully!': 'Working hours saved successfully!',
    'Theme Mode': 'Theme Mode',
    'Choose how the application looks': 'Choose how the application looks',
    'Default': 'Default',
    'Green': 'Green',
    'Indigo': 'Indigo',
    'Rose': 'Rose',
    'Cyan': 'Cyan',
    'New Appointment': 'New Appointment',
    'Patient Name': 'Patient Name',
    'Save Appointment': 'Save Appointment',
    'Personal Information': 'Personal Information',
    'Edit Profile': 'Edit Profile',
    'Booking Appointment Requests': 'Booking Appointment Requests',
    'No booking requests for now': 'No booking requests for now',
    'Request ID': 'Request ID',
    'Notice': 'Notice',
    'Accept': 'Accept',
    'Reject': 'Reject',
    'Request accepted successfully': 'Request accepted successfully',
    'Request rejected successfully': 'Request rejected successfully',
    'Treatment Plan': 'Treatment Plan',
    'Choose a patient and configure the lung cancer treatment plan.':
        'Choose a patient and configure the lung cancer treatment plan.',
    'Treatment Details': 'Treatment Details',
    'Lung Cancer Type *': 'Lung Cancer Type *',
    'Select lung cancer type': 'Select lung cancer type',
    'Treatment Type *': 'Treatment Type *',
    'Select treatment type': 'Select treatment type',
    'Additional Medicines': 'Additional Medicines',
    'Write additional medicines and dosage notes...':
        'Write additional medicines and dosage notes...',
    'Review Time Period *': 'Review Time Period *',
    'Select review period': 'Select review period',
    'Save Treatment Plan': 'Save Treatment Plan',
    'Common Medicines': 'Common Medicines',
    'Pick next review date': 'Pick next review date',
    'Next Review Date': 'Next Review Date',
    'Please complete all required fields.':
        'Please complete all required fields.',
    'Treatment plan saved successfully.': 'Treatment plan saved successfully.',
    'Patient *': 'Patient *',
    'Non-small cell lung cancer (NSCLC)': 'Non-small cell lung cancer (NSCLC)',
    'Small cell lung cancer (SCLC)': 'Small cell lung cancer (SCLC)',
    'Lung carcinoid tumor': 'Lung carcinoid tumor',
    'Mesothelioma': 'Mesothelioma',
    'Hormonal': 'Hormonal',
    'Weekly': 'Weekly',
    'Every 2 weeks': 'Every 2 weeks',
    'Monthly': 'Monthly',
    'Every 3 months': 'Every 3 months',
    'About Doctor': 'About Doctor',
    'Languages Spoken': 'Languages Spoken',
    'Professional Information': 'Professional Information',
    'Full Name': 'Full Name',
    'Work Place': 'Work Place',
    'Years of Experience': 'Years of Experience',
    'Location': 'Location',
    'Contact & Location': 'Contact & Location',
    'QR Code': 'QR Code',
    'QR Code Data': 'QR Code Data',
    'Share Profile': 'Share Profile',
    'Doctor Name': 'Doctor Name',
    'Specialization': 'Specialization',
    'Qualifications': 'Qualifications',
    'Consultation Fee': 'Consultation Fee',
    'Save QR Code': 'Save QR Code',
    'Regenerate QR': 'Regenerate QR',
    'Download QR': 'Download QR',
    'QR code downloaded successfully.': 'QR code downloaded successfully.',
    'Failed to download QR code.': 'Failed to download QR code.',
    'Failed to save profile.': 'Failed to save profile.',
    'QR preview is not ready yet.': 'QR preview is not ready yet.',
    'Could not export QR image.': 'Could not export QR image.',
    'ar, en': 'ar, en',
    'MBBS, MD': 'MBBS, MD',
    '50': '50',
    'Manage your application settings': 'Manage your application settings',
    'Delete': 'Delete',
    'Delete Account': 'Delete Account',
    'Confirm Delete': 'Confirm Delete',
    'This action is permanent and cannot be undone. Are you sure?':
        'This action is permanent and cannot be undone. Are you sure?',
    'Account deleted successfully': 'Account deleted successfully',
    'Failed to delete account. Please try again.':
        'Failed to delete account. Please try again.',
    'Please type delete keyword to confirm':
        'Please type delete or حذف to confirm',
    'Type delete keyword to continue.': 'Type delete or حذف to continue.',
    'Type delete keyword': 'Type delete or حذف',
    'Saving...': 'Saving...',
    'Cancer Diagnosis': 'Cancer Diagnosis',
    'Loading patients...': 'Loading patients...',
    'Retry': 'Retry',
    'Search and select patient': 'Search and select patient',
    'Search by name, phone, or ID': 'Search by name, phone, or ID',
    'New Patient Registration': 'New Patient Registration',
    'All fields marked with * are required':
        'All fields marked with * are required',
    'Sex': 'Sex',
    'Select sex': 'Select sex',
    'e.g., 2 weeks, 3 months': 'e.g., 2 weeks, 3 months',
    'Select Images': 'Select Images',
    'Clear All Fields': 'Clear All Fields',
    'years': 'years',
    'Failed to create patient': 'Failed to create patient',
    'Failed to create medical history': 'Failed to create medical history',
    'Add a patient to get started.': 'Add a patient to get started.',
    'Are you sure you want to delete this patient?':
        'Are you sure you want to delete this patient?',
    'Delete Patient': 'Delete Patient',
    'Enter full name': 'Enter full name',
    'Export Record': 'Export Record',
    'Failed to update patient': 'Failed to update patient',
    'File': 'File',
    'Size': 'Size',
    'Uploaded': 'Uploaded',
    'URL': 'URL',
    'bytes': 'bytes',
    'items': 'items',
    'Last Medical Record': 'Last Medical Record',
    'Last Record': 'Last Record',
    'Latest Treatment Plan': 'Latest Treatment Plan',
    'Medical Record': 'Medical Record',
    'No patients found': 'No patients found',
    'No treatment plan found': 'No treatment plan found',
    'No visible details were returned for this record.':
        'No visible details were returned for this record.',
    'Patient Details': 'Patient Details',
    'Patient History': 'Patient History',
    'Treatment History': 'Treatment History',
    'Search patients...': 'Search patients...',
    'Try a different search term.': 'Try a different search term.',
    'Try Again': 'Try Again',
    'Unknown date': 'Unknown date',
    'Uploaded image': 'Uploaded image',
    'plans': 'plans',
    'records': 'records',
    'Patient Phone': 'Patient Phone',
    'Patient Age': 'Patient Age',
    'Patient Sex': 'Patient Sex',
    'Family History': 'Family History',
    'Shortness of Breath': 'Shortness of Breath',
    'Coughing Blood': 'Coughing Blood',
    'Chest Pain': 'Chest Pain',
    'Fainting or Severe Dizziness': 'Fainting or Severe Dizziness',
    'Recent Weight Loss': 'Recent Weight Loss',
    'Smoker': 'Smoker',
    'Profession': 'Profession',
    'Hoarseness of Voice': 'Hoarseness of Voice',
    'Custom Question Answers': 'Custom Question Answers',
    'Images': 'Images',
    'Diagnosis Result': 'Diagnosis Result',
    'Created At': 'Created At',
    'Updated At': 'Updated At',
    'Phase': 'Phase',
    'Notes': 'Notes',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    'Lung Cancer Type': 'Lung Cancer Type',
    'Treatment Type': 'Treatment Type',
    'Review Time Period': 'Review Time Period',
    'Loading...': 'Loading...',
    'Refresh': 'Refresh',
    'No appointments found': 'No appointments found',
    'Patient Type': 'Patient Type',
    'Record': 'Record',
    'Request failed.': 'Request failed.',
    'Profile': 'Profile',
    'Select an existing patient or create a new one':
        'Select an existing patient or create a new one',
    'Search and choose from registered patients':
        'Search and choose from registered patients',
    'Register a new patient in the system':
        'Register a new patient in the system',
    'Select Patient': 'Select Patient',
  };

  static const Map<String, String> _ar = {
    'N/A': 'غير متاح',
    'Dashboard': 'لوحة التحكم',
    'Appointments': 'المواعيد',
    'Patients': 'المرضى',
    'Diagnosis': 'التشخيص',
    'Treatment Resistance': 'مقاومة العلاج',
    'Schedule': 'الجدول',
    'Settings': 'الإعدادات',
    'Doctor': 'طبيب',
    'Logout': 'تسجيل الخروج',
    'Toggle theme': 'تبديل النمط',
    'Light mode': 'الوضع الفاتح',
    'Dark mode': 'الوضع الداكن',
    'Logged out successfully': 'تم تسجيل الخروج بنجاح',
    'Page': 'صفحة',
    'CureVoo': 'كيورفو',
    'Welcome Back, Doctor': 'مرحباً بعودتك أيها الطبيب',
    'Sign in to access your dashboard': 'سجل الدخول للوصول إلى لوحة التحكم',
    'Email Address': 'البريد الإلكتروني',
    'Password': 'كلمة المرور',
    'Remember me': 'تذكرني',
    'Forgot Password?': 'نسيت كلمة المرور؟',
    'Sign In': 'تسجيل الدخول',
    'OR': 'أو',
    "Don't have an account? ": 'ليس لديك حساب؟ ',
    'Create Account': 'إنشاء حساب',
    'Why Choose CureVoo?': 'لماذا CureVoo؟',
    'Comprehensive Diagnosis & Treatment Plans': 'خطط تشخيص وعلاج شاملة',
    'Secure Patient Records Management': 'إدارة آمنة لسجلات المرضى',
    'Efficient Appointment Scheduling': 'جدولة مواعيد فعالة',
    'Please enter your email': 'يرجى إدخال البريد الإلكتروني',
    'Please enter your password': 'يرجى إدخال كلمة المرور',
    'Please enter a password': 'يرجى إدخال كلمة المرور',
    'Password must be at least 6 characters':
        'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
    'Password must be 12 to 128 characters':
        'يجب أن تكون كلمة المرور بين 12 و128 حرفاً',
    'Password must include a lowercase letter, uppercase letter, number, and symbol':
        'يجب أن تحتوي كلمة المرور على حرف صغير وحرف كبير ورقم ورمز',
    'Password must not contain spaces': 'يجب ألا تحتوي كلمة المرور على مسافات',
    'Forgot Password': 'نسيت كلمة المرور',
    'Verify OTP': 'التحقق من الرمز',
    'Enter the OTP sent to your email.':
        'أدخل الرمز المرسل إلى بريدك الإلكتروني.',
    'OTP Code': 'رمز التحقق',
    '6-digit code': 'رمز من 6 أرقام',
    'Please enter the OTP': 'يرجى إدخال رمز التحقق',
    'OTP must be 6 digits': 'يجب أن يكون رمز التحقق مكون من 6 أرقام',
    'Demo OTP: 123456': 'رمز تجريبي: 123456',
    'Invalid OTP. Please try again.': 'رمز التحقق غير صحيح. حاول مرة أخرى.',
    'OTP verified successfully.': 'تم التحقق من الرمز بنجاح',
    'Reset Password': 'إعادة تعيين كلمة المرور',
    'Create a new password for your account.': 'أنشئ كلمة مرور جديدة لحسابك.',
    'New Password': 'كلمة المرور الجديدة',
    'Confirm Password': 'تأكيد كلمة المرور',
    'Please enter a new password': 'يرجى إدخال كلمة مرور جديدة',
    'Please confirm your password': 'يرجى تأكيد كلمة المرور',
    'Passwords do not match': 'كلمتا المرور غير متطابقتين',
    'Save New Password': 'حفظ كلمة المرور الجديدة',
    'Password updated successfully.': 'تم تحديث كلمة المرور بنجاح',
    'Change Password': 'تغيير كلمة المرور',
    'Current Password': 'كلمة المرور الحالية',
    'Enter your current password': 'أدخل كلمة المرور الحالية',
    'Enter your new password': 'أدخل كلمة المرور الجديدة',
    'Confirm your new password': 'أكد كلمة المرور الجديدة',
    'Please enter your current password': 'يرجى إدخال كلمة المرور الحالية',
    'Update your password by entering your current password first.':
        'قم بتحديث كلمة المرور عن طريق إدخال كلمة المرور الحالية أولاً.',
    'Password changed successfully.': 'تم تغيير كلمة المرور بنجاح.',
    'Failed to change password. Please try again.':
        'فشل تغيير كلمة المرور. يرجى المحاولة مرة أخرى.',
    'New password must be different from current password':
        'يجب أن تكون كلمة المرور الجديدة مختلفة عن الحالية',
    'Dashboard Overview': 'نظرة عامة على لوحة التحكم',
    'Total Patients': 'إجمالي المرضى',
    'Upcoming Appointments': 'المواعيد القادمة',
    'Pending Appointments': 'المواعيد المعلقة',
    'Latest AI Prediction': 'أحدث تنبؤ بالذكاء الاصطناعي',
    'Welcome back, Dr.': 'مرحباً بعودتك، د.',
    "Here's what's happening today.": 'إليك ما يحدث اليوم.',
    "Welcome back, Dr. Johnson! Here's what's happening today.":
        'مرحباً د. جونسون، هذا ملخص أحداث اليوم.',
    'Appointment Management': 'إدارة المواعيد',
    'Manage and schedule patient appointments': 'إدارة وجدولة مواعيد المرضى',
    'Create a new appointment for a patient': 'إنشاء موعد جديد لمريض',
    'Edit Appointment': 'تعديل الموعد',
    'Update Appointment': 'تحديث الموعد',
    'Update appointment details': 'تحديث تفاصيل الموعد',
    'Select patient': 'اختر المريض',
    'Phone Number': 'رقم الهاتف',
    'Date': 'التاريخ',
    'Select date': 'اختر التاريخ',
    'Select time': 'اختر الوقت',
    'Appointment Type': 'نوع الموعد',
    'Select appointment type': 'اختر نوع الموعد',
    'Please select a patient': 'يرجى اختيار المريض',
    'Please select a date': 'يرجى اختيار التاريخ',
    'Please select time': 'يرجى اختيار الوقت',
    'Please select appointment type': 'يرجى اختيار نوع الموعد',
    'Additional Notes': 'ملاحظات إضافية',
    'Add notes': 'أضف ملاحظات',
    'Status': 'الحالة',
    'Appointment created successfully': 'تم إنشاء الموعد بنجاح',
    'Appointment updated successfully': 'تم تحديث الموعد بنجاح',
    'Appointment deleted successfully': 'تم حذف الموعد بنجاح',
    'Delete Appointment': 'حذف الموعد',
    'Are you sure you want to delete this appointment?':
        'هل أنت متأكد أنك تريد حذف هذا الموعد؟',
    'Failed to delete appointment.': 'فشل حذف الموعد.',
    'Appointment Details': 'تفاصيل الموعد',
    'All Appointments': 'جميع المواعيد',
    'Search appointments...': 'ابحث في المواعيد...',
    'Date Range': 'نطاق التاريخ',
    'Time': 'الوقت',
    'Type': 'النوع',
    'View': 'عرض',
    'Confirmed': 'مؤكد',
    'Pending': 'قيد الانتظار',
    'Cancelled': 'ملغي',
    'Check-up': 'فحص',
    'Follow-up': 'متابعة',
    'Consultation': 'استشارة',
    'Vaccination': 'تطعيم',
    'Emergency': 'طارئ',
    'Routine': 'روتيني',
    "Today's Appointments": 'مواعيد اليوم',
    'Recent Patients': 'المرضى الأخيرون',
    'Weekly Schedule': 'الجدول الأسبوعي',
    'View and manage your weekly appointments': 'عرض وإدارة مواعيدك الأسبوعية',
    'Nov 16 - Nov 22, 2025': '16 نوفمبر - 22 نوفمبر 2025',
    'This Week': 'هذا الأسبوع',
    'All Patients': 'كل المرضى',
    'Filter': 'تصفية',
    'Add New Patient': 'إضافة مريض جديد',
    'Cancel': 'إلغاء',
    'Patient added successfully!': 'تمت إضافة المريض بنجاح',
    'Please fill all fields': 'يرجى تعبئة جميع الحقول',
    'Add Patient': 'إضافة مريض',
    'Close': 'إغلاق',
    'Edit': 'تعديل',
    'Edit Patient': 'تعديل المريض',
    'Patient updated successfully!': 'تم تحديث بيانات المريض بنجاح',
    'Update': 'تحديث',
    'Patient Management': 'إدارة المرضى',
    'View and manage patient records': 'عرض وإدارة سجلات المرضى',
    'Patient': 'المريض',
    'Age': 'العمر',
    'Gender': 'الجنس',
    'Phone': 'الهاتف',
    'Last Visit': 'آخر زيارة',
    'Condition': 'الحالة',
    'Actions': 'الإجراءات',
    'Language': 'اللغة',
    'Application Language': 'لغة التطبيق',
    'Choose your preferred language': 'اختر لغتك المفضلة',
    'English': 'الإنجليزية',
    'Arabic': 'العربية',
    'to': 'إلى',
    'Collapse sidebar': 'تصغير الشريط الجانبي',
    'Expand sidebar': 'توسيع الشريط الجانبي',
    'Cancer Diagnosis & Examination': 'تشخيص السرطان والفحص',
    'Complete the diagnostic form and upload X-ray images for analysis':
        'أكمل نموذج التشخيص وارفع صور الأشعة للتحليل',
    'Patient Selection': 'اختيار المريض',
    'Choose an option': 'اختر خياراً',
    'Select Existing Patient': 'اختر مريضاً موجوداً',
    'Create New Patient': 'إنشاء مريض جديد',
    'Patient Selected': 'تم اختيار المريض',
    'Creating New Patient': 'إنشاء مريض جديد',
    'Please fill in the patient information below':
        'يرجى تعبئة معلومات المريض أدناه',
    'Select Patient *': 'اختر المريض *',
    'Choose a patient from the list': 'اختر مريضاً من القائمة',
    'Patient Information': 'معلومات المريض',
    'Enter patient name': 'أدخل اسم المريض',
    'Enter age': 'أدخل العمر',
    'Select gender': 'اختر الجنس',
    'Patient ID': 'رقم المريض',
    'Enter patient ID': 'أدخل رقم المريض',
    'Patient information auto-filled from selected patient':
        'تم تعبئة معلومات المريض تلقائياً من المريض المحدد',
    'Cancer Type & Location': 'نوع السرطان وموقعه',
    'Cancer Type': 'نوع السرطان',
    'Select cancer type': 'اختر نوع السرطان',
    'Tumor Location': 'موقع الورم',
    'Specify exact location': 'حدد الموقع بدقة',
    'Tumor Size (cm)': 'حجم الورم (سم)',
    'Enter tumor size': 'أدخل حجم الورم',
    'Symptoms & Medical History': 'الأعراض والتاريخ الطبي',
    'Current Symptoms': 'الأعراض الحالية',
    'Describe current symptoms': 'صف الأعراض الحالية',
    'Symptom Duration': 'مدة الأعراض',
    'Do you suffer from shortness of breath?': 'هل تعاني من ضيق في التنفس؟',
    'Is there a cough accompanied by blood?': 'هل هناك سعال مصحوب بدم؟',
    'Is there chest pain?': 'هل هناك ألم في الصدر؟',
    'Has fainting or severe dizziness occurred?': 'هل حدث إغماء أو دوخة شديدة؟',
    'Has there been weight loss in the recent period?':
        'هل هناك فقدان في الوزن خلال الفترة الأخيرة؟',
    'Are you a smoker?': 'هل أنت مدخن؟',
    'What is your profession?': 'ما هي مهنتك؟',
    'Enter profession': 'أدخل المهنة',
    'Is there hoarseness of voice?': 'هل هناك بحة في الصوت؟',
    'Family History of Cancer': 'تاريخ عائلي للإصابة بالسرطان',
    'Select option': 'اختر خياراً',
    'Previous Treatment History': 'تاريخ العلاجات السابقة',
    'List previous treatments, surgeries, or therapies':
        'اذكر العلاجات أو العمليات الجراحية أو الجلسات السابقة',
    'Additional Questions & Answers': 'أسئلة وإجابات إضافية',
    'Add question and answer': 'أضف سؤالاً وإجابة',
    'Symptoms Section Notes': 'ملاحظات قسم الأعراض',
    'Add notes related to symptoms and medical history':
        'أضف ملاحظات متعلقة بالأعراض والتاريخ الطبي',
    'Question': 'السؤال',
    'Enter question': 'أدخل السؤال',
    'Answer': 'الإجابة',
    'Enter answer': 'أدخل الإجابة',
    'Remove': 'إزالة',
    'Clinical Examination Findings': 'نتائج الفحص السريري',
    'Blood Pressure': 'ضغط الدم',
    'e.g., 120/80 mmHg': 'مثال: 120/80 ملم زئبق',
    'Heart Rate': 'معدل ضربات القلب',
    'e.g., 72 bpm': 'مثال: 72 نبضة في الدقيقة',
    'Temperature': 'درجة الحرارة',
    'e.g., 37°C': 'مثال: 37°م',
    'Weight (kg)': 'الوزن (كغ)',
    'Enter weight': 'أدخل الوزن',
    'Physical Examination Notes': 'ملاحظات الفحص البدني',
    'Document physical examination findings': 'دوّن نتائج الفحص البدني',
    'Laboratory Test Results': 'نتائج الفحوصات المخبرية',
    'Blood Test Results': 'نتائج تحليل الدم',
    'CBC, tumor markers, liver function, kidney function...':
        'صورة دم، مؤشرات الأورام، وظائف الكبد، وظائف الكلى...',
    'Biopsy Results (if available)': 'نتائج الخزعة (إن وجدت)',
    'Histopathology findings, cell type, grade...':
        'نتائج علم الأمراض، نوع الخلايا، الدرجة...',
    'Cancer Staging Information': 'معلومات مرحلة السرطان',
    'Select stage': 'اختر المرحلة',
    'Additional Clinical Notes': 'ملاحظات سريرية إضافية',
    "Doctor's Notes & Observations": 'ملاحظات الطبيب ومشاهداته',
    'Any additional observations, concerns, or recommendations...':
        'أي ملاحظات أو مخاوف أو توصيات إضافية...',
    'X-Ray Image Upload': 'رفع صور الأشعة',
    'Click to upload X-ray images': 'انقر لرفع صور الأشعة',
    'PNG, JPG, DICOM up to 10MB': 'PNG، JPG، DICOM حتى 10 ميغابايت',
    'Uploaded X-Ray Images': 'صور الأشعة المرفوعة',
    'Diagnosis Stats': 'إحصائيات التشخيص',
    'Total Cases': 'إجمالي الحالات',
    'This Month': 'هذا الشهر',
    'Pending Review': 'قيد المراجعة',
    'Generate Diagnosis Report': 'إنشاء تقرير التشخيص',
    'Diagnosis Report': 'تقرير التشخيص',
    'Download PDF': 'تحميل PDF',
    'Print Report': 'طباعة التقرير',
    'Share': 'مشاركة',
    'Diagnosis result summary':
        'بناءً على المعلومات المقدمة وصور الأشعة، يشير التحليل الأولي إلى الحاجة إلى مزيد من الفحص. يرجى مراجعة التقرير الشامل أدناه للحصول على النتائج والتوصيات التفصيلية.',
    'Diagnosis report generated successfully!': 'تم إنشاء تقرير التشخيص بنجاح!',
    'Male': 'ذكر',
    'Female': 'أنثى',
    'Other': 'آخر',
    'Lung Cancer': 'سرطان الرئة',
    'Breast Cancer': 'سرطان الثدي',
    'Prostate Cancer': 'سرطان البروستاتا',
    'Colorectal Cancer': 'سرطان القولون والمستقيم',
    'Skin Cancer': 'سرطان الجلد',
    'Lymphoma': 'لمفوما',
    'Leukemia': 'لوكيميا',
    'Yes': 'نعم',
    'No': 'لا',
    'Unknown': 'غير معروف',
    'Stage 0 (In situ)': 'المرحلة 0 (موضعي)',
    'Stage I': 'المرحلة الأولى',
    'Stage II': 'المرحلة الثانية',
    'Stage III': 'المرحلة الثالثة',
    'Stage IV': 'المرحلة الرابعة',
    'Not yet determined': 'لم يتم تحديدها بعد',
    'years old': 'سنة',
    'y': 'س',
    'ID': 'رقم',
    'Manage your clinic and application settings':
        'إدارة إعدادات العيادة والتطبيق',
    'Profile Information': 'معلومات الملف الشخصي',
    'First Name': 'الاسم الأول',
    'Enter first name': 'أدخل الاسم الأول',
    'Last Name': 'اسم العائلة',
    'Enter last name': 'أدخل اسم العائلة',
    'Email': 'البريد الإلكتروني',
    'Enter email': 'أدخل البريد الإلكتروني',
    'Enter phone number': 'أدخل رقم الهاتف',
    'Specialty': 'التخصص',
    'Enter specialty': 'أدخل التخصص',
    'Save Changes': 'حفظ التغييرات',
    'Profile information saved successfully!':
        'تم حفظ معلومات الملف الشخصي بنجاح!',
    'Clinic Settings': 'إعدادات العيادة',
    'Clinic Name': 'اسم العيادة',
    'Enter clinic name': 'أدخل اسم العيادة',
    'Address': 'العنوان',
    'Enter address': 'أدخل العنوان',
    'City': 'المدينة',
    'Enter city': 'أدخل المدينة',
    'ZIP Code': 'الرمز البريدي',
    'Enter ZIP code': 'أدخل الرمز البريدي',
    'Update Clinic Info': 'تحديث معلومات العيادة',
    'Clinic information updated successfully!':
        'تم تحديث معلومات العيادة بنجاح!',
    'Notifications': 'الإشعارات',
    'Email Notifications': 'إشعارات البريد الإلكتروني',
    'Receive email updates about appointments':
        'استلم تحديثات البريد الإلكتروني حول المواعيد',
    'SMS Notifications': 'إشعارات الرسائل النصية',
    'Get text messages for urgent updates':
        'استلم رسائل نصية للتحديثات العاجلة',
    'Appointment Reminders': 'تذكيرات المواعيد',
    'Send reminders to patients': 'أرسل تذكيرات للمرضى',
    'Daily Summary': 'الملخص اليومي',
    'Receive daily summary of appointments': 'استلم ملخصاً يومياً للمواعيد',
    'enabled': 'مفعل',
    'disabled': 'معطل',
    'Working Hours': 'ساعات العمل',
    'Monday': 'الاثنين',
    'Tuesday': 'الثلاثاء',
    'Wednesday': 'الأربعاء',
    'Thursday': 'الخميس',
    'Friday': 'الجمعة',
    'Saturday': 'السبت',
    'Sunday': 'الأحد',
    'Save Working Hours': 'حفظ ساعات العمل',
    'Working hours saved successfully!': 'تم حفظ ساعات العمل بنجاح!',
    'Theme Mode': 'وضع السمة',
    'Choose how the application looks': 'اختر كيف سيظهر التطبيق',
    'Default': 'الافتراضي',
    'Green': 'أخضر',
    'Indigo': 'نيلي',
    'Rose': 'وردي',
    'Cyan': 'سماوي',
    'New Appointment': 'موعد جديد',
    'Patient Name': 'اسم المريض',
    'Save Appointment': 'حفظ الموعد',
    'Personal Information': 'المعلومات الشخصية',
    'Edit Profile': 'تعديل الملف الشخصي',
    'Booking Appointment Requests': 'طلبات حجز المواعيد',
    'No booking requests for now': 'لا توجد طلبات حجز حالياً',
    'Request ID': 'رقم الطلب',
    'Notice': 'ملاحظة',
    'Accept': 'قبول',
    'Reject': 'رفض',
    'Request accepted successfully': 'تم قبول الطلب بنجاح',
    'Request rejected successfully': 'تم رفض الطلب بنجاح',
    'Treatment Plan': 'خطة العلاج',
    'Choose a patient and configure the lung cancer treatment plan.':
        'اختر المريض وقم بإعداد خطة علاج سرطان الرئة.',
    'Treatment Details': 'تفاصيل العلاج',
    'Lung Cancer Type *': 'نوع سرطان الرئة *',
    'Select lung cancer type': 'اختر نوع سرطان الرئة',
    'Treatment Type *': 'نوع العلاج *',
    'Select treatment type': 'اختر نوع العلاج',
    'Additional Medicines': 'الأدوية الإضافية',
    'Write additional medicines and dosage notes...':
        'اكتب الأدوية الإضافية وملاحظات الجرعات...',
    'Review Time Period *': 'فترة المراجعة *',
    'Select review period': 'اختر فترة المراجعة',
    'Save Treatment Plan': 'حفظ خطة العلاج',
    'Common Medicines': 'الأدوية الشائعة',
    'Pick next review date': 'اختر تاريخ المراجعة القادم',
    'Next Review Date': 'تاريخ المراجعة القادم',
    'Please complete all required fields.': 'يرجى إكمال جميع الحقول المطلوبة.',
    'Treatment plan saved successfully.': 'تم حفظ خطة العلاج بنجاح.',
    'Patient *': 'المريض *',
    'Non-small cell lung cancer (NSCLC)': 'سرطان الرئة ذو الخلايا غير الصغيرة',
    'Small cell lung cancer (SCLC)': 'سرطان الرئة ذو الخلايا الصغيرة',
    'Lung carcinoid tumor': 'ورم سرطاوي رئوي',
    'Mesothelioma': 'ورم المتوسطة',
    'Hormonal': 'هرموني',
    'Weekly': 'أسبوعياً',
    'Every 2 weeks': 'كل أسبوعين',
    'Monthly': 'شهرياً',
    'Every 3 months': 'كل 3 أشهر',
    'About Doctor': 'نبذة عن الطبيب',
    'Languages Spoken': 'اللغات المتحدث بها',
    'Professional Information': 'المعلومات المهنية',
    'Full Name': 'الاسم الكامل',
    'Work Place': 'مكان العمل',
    'Years of Experience': 'سنوات الخبرة',
    'Location': 'الموقع',
    'Contact & Location': 'التواصل والموقع',
    'QR Code': 'رمز QR',
    'QR Code Data': 'بيانات رمز QR',
    'Share Profile': 'مشاركة الملف الشخصي',
    'Doctor Name': 'اسم الطبيب',
    'Specialization': 'التخصص',
    'Qualifications': 'المؤهلات',
    'Consultation Fee': 'رسوم الاستشارة',
    'Save QR Code': 'حفظ رمز QR',
    'Regenerate QR': 'إعادة إنشاء رمز QR',
    'Download QR': 'تنزيل رمز QR',
    'QR code downloaded successfully.': 'تم تنزيل رمز QR بنجاح.',
    'Failed to download QR code.': 'فشل تنزيل رمز QR.',
    'Failed to save profile.': 'فشل حفظ الملف الشخصي.',
    'QR preview is not ready yet.': 'معاينة رمز QR غير جاهزة بعد.',
    'Could not export QR image.': 'تعذر تصدير صورة رمز QR.',
    'ar, en': 'ar, en',
    'MBBS, MD': 'MBBS, MD',
    '50': '50',
    'Manage your application settings': 'إدارة إعدادات التطبيق',
    'Delete': 'حذف',
    'Delete Account': 'حذف الحساب',
    'Confirm Delete': 'تأكيد الحذف',
    'This action is permanent and cannot be undone. Are you sure?':
        'هذا الإجراء دائم ولا يمكن التراجع عنه. هل أنت متأكد؟',
    'Account deleted successfully': 'تم حذف الحساب بنجاح',
    'Failed to delete account. Please try again.':
        'فشل حذف الحساب. يرجى المحاولة مرة أخرى.',
    'Please type delete keyword to confirm': 'يرجى كتابة delete أو حذف للتأكيد',
    'Type delete keyword to continue.': 'اكتب delete أو حذف للمتابعة.',
    'Type delete keyword': 'اكتب delete أو حذف',
    'Saving...': 'جارٍ الحفظ...',
    'Cancer Diagnosis': 'تشخيص السرطان',
    'Loading patients...': 'جارٍ تحميل المرضى...',
    'Retry': 'إعادة المحاولة',
    'Search and select patient': 'ابحث واختر المريض',
    'Search by name, phone, or ID': 'ابحث بالاسم أو الهاتف أو رقم المعرف',
    'New Patient Registration': 'تسجيل مريض جديد',
    'All fields marked with * are required': 'كل الحقول التي تحمل * مطلوبة',
    'Sex': 'الجنس',
    'Select sex': 'اختر الجنس',
    'e.g., 2 weeks, 3 months': 'مثال: أسبوعان، 3 أشهر',
    'Select Images': 'اختر الصور',
    'Clear All Fields': 'مسح جميع الحقول',
    'years': 'سنة',
    'Failed to create patient': 'فشل إنشاء المريض',
    'Failed to create medical history': 'فشل إنشاء السجل الطبي',
    'Add a patient to get started.': 'أضف مريضًا للبدء.',
    'Are you sure you want to delete this patient?':
        'هل أنت متأكد أنك تريد حذف هذا المريض؟',
    'Delete Patient': 'حذف المريض',
    'Enter full name': 'أدخل الاسم الكامل',
    'Export Record': 'تصدير السجل',
    'Failed to update patient': 'فشل تحديث بيانات المريض',
    'File': 'الملف',
    'Size': 'الحجم',
    'Uploaded': 'تم الرفع',
    'URL': 'الرابط',
    'bytes': 'بايت',
    'items': 'عناصر',
    'Last Medical Record': 'آخر سجل طبي',
    'Last Record': 'آخر سجل',
    'Latest Treatment Plan': 'أحدث خطة علاج',
    'Medical Record': 'السجل الطبي',
    'No patients found': 'لم يتم العثور على مرضى',
    'No treatment plan found': 'لم يتم العثور على خطة علاج',
    'No visible details were returned for this record.':
        'لم يتم إرجاع تفاصيل مرئية لهذا السجل.',
    'Patient Details': 'تفاصيل المريض',
    'Patient History': 'تاريخ المريض',
    'Treatment History': 'سجل العلاج',
    'Search patients...': 'ابحث عن المرضى...',
    'Try a different search term.': 'جرّب كلمة بحث مختلفة.',
    'Try Again': 'حاول مرة أخرى',
    'Unknown date': 'تاريخ غير معروف',
    'Uploaded image': 'صورة مرفوعة',
    'plans': 'خطط',
    'records': 'سجلات',
    'Patient Phone': 'هاتف المريض',
    'Patient Age': 'عمر المريض',
    'Patient Sex': 'جنس المريض',
    'Family History': 'التاريخ العائلي',
    'Shortness of Breath': 'ضيق التنفس',
    'Coughing Blood': 'سعال مصحوب بدم',
    'Chest Pain': 'ألم الصدر',
    'Fainting or Severe Dizziness': 'إغماء أو دوخة شديدة',
    'Recent Weight Loss': 'فقدان وزن حديث',
    'Smoker': 'مدخن',
    'Profession': 'المهنة',
    'Hoarseness of Voice': 'بحة في الصوت',
    'Custom Question Answers': 'إجابات أسئلة مخصصة',
    'Images': 'الصور',
    'Diagnosis Result': 'نتيجة التشخيص',
    'Created At': 'تاريخ الإنشاء',
    'Updated At': 'تاريخ التحديث',
    'Phase': 'المرحلة',
    'Notes': 'ملاحظات',
    'Start Date': 'تاريخ البدء',
    'End Date': 'تاريخ الانتهاء',
    'Lung Cancer Type': 'نوع سرطان الرئة',
    'Treatment Type': 'نوع العلاج',
    'Review Time Period': 'فترة المراجعة',
    'Loading...': 'جارٍ التحميل...',
    'Refresh': 'تحديث',
    'No appointments found': 'لا توجد مواعيد',
    'Patient Type': 'نوع المريض',
    'Record': 'سجل',
    'Request failed.': 'فشل الطلب.',
    'You cannot add appointments to past days':
        'لا يمكنك إضافة مواعيد لأيام سابقة',
    'Profile': 'الملف الشخصي',
    'Select an existing patient or create a new one':
        'اختر مريض موجود أو أنشئ مريض جديد',
    'Search and choose from registered patients':
        'ابحث واختر من المرضى المسجلين',
    'Register a new patient in the system': 'سجل مريض جديد في النظام',
    'Select Patient': 'اختر مريضاً',
  };

  String tr(String key) {
    if (key.isEmpty) return '';
    if (locale.languageCode == 'ar') {
      return _ar[key] ?? key;
    }
    return _en[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationBuildContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this).tr(key);
}
